database:
  driverClass: org.h2.Driver
  user: sa
  password:
  url: jdbc:h2:file:./target/kanban

  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.H2Dialect

  maxWaitForConnection: 1s

  validationQuery: "/* MyApplication Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false


server:
  rootPath: '/api/*'
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081